package main

var questionsL1 = questionBank{
	[]question{
		{question: "How many letters are in the Arabic alphabet?",
			answer1: answer{text: "28", isCorrect: false},
			answer2: answer{text: "29", isCorrect: true},
			answer3: answer{text: "30", isCorrect: false}},
		{question: "What are the three vowel signs in Arabic?",
			answer1: answer{text: "Hamza, Kusrah, Dummah", isCorrect: false},
			answer2: answer{text: "Alif Ba Ta", isCorrect: false},
			answer3: answer{text: "Fatah, Kusrah, Dummah", isCorrect: true}},
		{question: "What are the three word types in Arabic?",
			answer1: answer{text: "Verb, Noun, Particle", isCorrect: true},
			answer2: answer{text: "Verb, Adjective, Noun", isCorrect: false},
			answer3: answer{text: "Proper Noun, Adverb, Verb", isCorrect: false}},
		{question: "أ When we say this letter it is?",
			answer1: answer{text: "Alif", isCorrect: false},
			answer2: answer{text: "Hamza", isCorrect: true},
			answer3: answer{text: "Kasrah", isCorrect: false}},
		{question: "  هَـٰذَا مَسْجِدٌ",
			answer1: answer{text: "This is a door", isCorrect: false},
			answer2: answer{text: "This is a house", isCorrect: false},
			answer3: answer{text: "This is a mosque", isCorrect: true}},
		{question: "Tanween is a _____ on the last letter of a noun?",
			answer1: answer{text: "double vowel sound", isCorrect: true},
			answer2: answer{text: "triple vowel sound", isCorrect: false},
			answer3: answer{text: "doubles the ending letter sound", isCorrect: false}},
		{question: " ال is used before what kind of nouns?",
			answer1: answer{text: "Indefinite nouns", isCorrect: false},
			answer2: answer{text: "Proper Nouns", isCorrect: false},
			answer3: answer{text: "Definite Nouns", isCorrect: true}},
		{question: "المجرور (al-majrūr) is_____case and ____ sound?",
			answer1: answer{text: "Accusative / Fathah", isCorrect: false},
			answer2: answer{text: "Genative / Kusrah", isCorrect: true},
			answer3: answer{text: "Nominative /dummah", isCorrect: false}},
	},
}
var questionsL2 = questionBank{
	[]question{
		{question: "What is the meaning of هذا?",
			answer1: answer{text: "That", isCorrect: false},
			answer2: answer{text: "During", isCorrect: false},
			answer3: answer{text: "This", isCorrect: true}},
		{question: "What are copula verbs in Arabic?",
			answer1: answer{text: "They don't exist in Arabic", isCorrect: true},
			answer2: answer{text: "They occur after هذا ", isCorrect: false},
			answer3: answer{text: "They link the parts of the sentences", isCorrect: false}},
		{question: "ما is to ask about?",
			answer1: answer{text: "People", isCorrect: false},
			answer2: answer{text: "Things", isCorrect: true},
			answer3: answer{text: "Places", isCorrect: false}},
		{question: "أَقْالَم means?",
			answer1: answer{text: "People", isCorrect: false},
			answer2: answer{text: "a pen", isCorrect: false},
			answer3: answer{text: "pens", isCorrect: true}},
		{question: "When shaddah is on a letter it means?",
			answer1: answer{text: "The letter is doubled", isCorrect: true},
			answer2: answer{text: "The letter is followed by a long vowel", isCorrect: false},
			answer3: answer{text: "The letter doesn't have a vowel sound", isCorrect: false}},
		{question: "ذلك means?",
			answer1: answer{text: "This masculine", isCorrect: false},
			answer2: answer{text: "That feminine", isCorrect: false},
			answer3: answer{text: "That masculine", isCorrect: true}},
		{question: "الحمير means?",
			answer1: answer{text: "The horses", isCorrect: true},
			answer2: answer{text: "The horse", isCorrect: false},
			answer3: answer{text: "A horse", isCorrect: false}},
	},
}

var questionsL3 = questionBank{
	[]question{
		{question: "هذا كتاب means?",
			answer1: answer{text: "That is a book", isCorrect: false},
			answer2: answer{text: "This is a book", isCorrect: true},
			answer3: answer{text: "That is the book", isCorrect: false}},
		{question: "هذا محمدmeans?",
			answer1: answer{text: "That is Muhammad", isCorrect: false},
			answer2: answer{text: "Who is Muhammad?", isCorrect: false},
			answer3: answer{text: "This is Muhammad", isCorrect: true}},
		{question: "  ذلك رجل means?",
			answer1: answer{text: "That is a man", isCorrect: true},
			answer2: answer{text: "This is a man", isCorrect: false},
			answer3: answer{text: "There is a man", isCorrect: false}},
		{question: "Nominal sentence starts with a?",
			answer1: answer{text: "verb", isCorrect: false},
			answer2: answer{text: "preposition", isCorrect: false},
			answer3: answer{text: "noun", isCorrect: true}},
		{question: "خبر Means?",
			answer1: answer{text: "subject/news", isCorrect: false},
			answer2: answer{text: "predicate/news", isCorrect: true},
			answer3: answer{text: "letter/news", isCorrect: false}},
		{question: "المنزل قريبWhere is the predicate?(khabr)",
			answer1: answer{text: " قريب", isCorrect: true},
			answer2: answer{text: "There is no khabr", isCorrect: false},
			answer3: answer{text: "المنزل", isCorrect: false}},

		{question: "قمصان means",
			answer1: answer{text: "shirts", isCorrect: true},
			answer2: answer{text: "The shirt", isCorrect: false},
			answer3: answer{text: "a shirt", isCorrect: false}},
	},
}

var questionsL4 = questionBank{
	[]question{
		{question: "In Arabic there are ____ kinds of sentences?",
			answer1: answer{text: "1", isCorrect: false},
			answer2: answer{text: "2", isCorrect: true},
			answer3: answer{text: "3", isCorrect: false}},
		{question: "Marfu'a or nominative noun takes",
			answer1: answer{text: "dummah", isCorrect: true},
			answer2: answer{text: "kasrah", isCorrect: false},
			answer3: answer{text: "fattah", isCorrect: false}},
		{question: "القمر جميل in this sentence جميل is not_____?",
			answer1: answer{text: "indefinate", isCorrect: false},
			answer2: answer{text: "singular", isCorrect: false},
			answer3: answer{text: "definate", isCorrect: true}},
		{question: "Nominal sentences' subject is usually?",
			answer1: answer{text: "genitive case", isCorrect: false},
			answer2: answer{text: "accusative case", isCorrect: false},
			answer3: answer{text: "nominative case", isCorrect: true}},
		{question: "The hamza is above or below the alif",
			answer1: answer{text: "Hamza Alwassil", isCorrect: false},
			answer2: answer{text: "Hamza Alqatta'a", isCorrect: true},
			answer3: answer{text: "Hamza Almaad", isCorrect: false}},
		{question: "When is Hamza Alwassil is pronounced?",
			answer1: answer{text: "When connected to another word", isCorrect: false},
			answer2: answer{text: "Always", isCorrect: false},
			answer3: answer{text: "At the beginning of speech", isCorrect: true}},

		{question: "Words starting with Alif lam are Hamza____?",
			answer1: answer{text: "Alqatta'a", isCorrect: false},
			answer2: answer{text: "AlWassil", isCorrect: true},
			answer3: answer{text: "No Hamza", isCorrect: false}},
	},
}

var questionsL5 = questionBank{
	[]question{
		{question: "الأقارب means?",
			answer1: answer{text: "relative", isCorrect: false},
			answer2: answer{text: "near by", isCorrect: false},
			answer3: answer{text: "relatives", isCorrect: true}},
		{question: "والكتاب is pronounced as ",
			answer1: answer{text: "one word", isCorrect: true},
			answer2: answer{text: "two words", isCorrect: false},
			answer3: answer{text: "three words", isCorrect: false}},
		{question: "There are ____ moon letters?",
			answer1: answer{text: "13", isCorrect: false},
			answer2: answer{text: "14", isCorrect: true},
			answer3: answer{text: "15", isCorrect: false}},
		{question: "The letter ba ب is a ______ letter?",
			answer1: answer{text: "moon", isCorrect: true},
			answer2: answer{text: "sun", isCorrect: false},
			answer3: answer{text: "earth", isCorrect: false}},
		{question: "The letter after Alif Lam has a ______ if it's a moon letter?",
			answer1: answer{text: "shaddah", isCorrect: false},
			answer2: answer{text: "sukoon", isCorrect: true},
			answer3: answer{text: "kasrah", isCorrect: false}},
		{question: "The letter after Alif Lam has a ______ if it's a sun letter?",
			answer1: answer{text: "shaddah", isCorrect: true},
			answer2: answer{text: "sukoon", isCorrect: false},
			answer3: answer{text: "kasrah", isCorrect: false}},

		{question: "Lam in Alif Alam is not pronounced if the letter after it is___________?",
			answer1: answer{text: "moon letter", isCorrect: false},
			answer2: answer{text: "earth letter", isCorrect: false},
			answer3: answer{text: "sun letter", isCorrect: true}},
	},
}

//TODO: Make lesson about hamzas
var questionsL6 = questionBank{
	[]question{
		{question: "Plural of father",
			answer1: answer{text: "الآب", isCorrect: false},
			answer2: answer{text: "لآباء", isCorrect: true},
			answer3: answer{text: "أخت", isCorrect: false}},
		{question: "Plural of mouth ",
			answer1: answer{text: "أفواه", isCorrect: true},
			answer2: answer{text: "فمنا", isCorrect: false},
			answer3: answer{text: "فم", isCorrect: false}},
		{question: "Arabic nouns have how many case endings?",
			answer1: answer{text: "3", isCorrect: true},
			answer2: answer{text: "4", isCorrect: false},
			answer3: answer{text: "0", isCorrect: false}},
		{question: "The noun after في is ?",
			answer1: answer{text: "accusative/fatah", isCorrect: false},
			answer2: answer{text: "instrumental/dummah", isCorrect: false},
			answer3: answer{text: "genitive/kasrah", isCorrect: true}},
		{question: "Which is not an Arabic case ending?",
			answer1: answer{text: "nominative/dummah", isCorrect: false},
			answer2: answer{text: "dative/kasrah", isCorrect: true},
			answer3: answer{text: "genitive/kasrah", isCorrect: false}},
		{question: "في السيارة ends with?",
			answer1: answer{text: "shaddah", isCorrect: false},
			answer2: answer{text: "kasrahtain", isCorrect: false},
			answer3: answer{text: "kasrah", isCorrect: true}},

		{question: "Prepositional phrase in Arabic is a preposition followed by a_____?",
			answer1: answer{text: "noun", isCorrect: true},
			answer2: answer{text: "verb", isCorrect: false},
			answer3: answer{text: "another preposition", isCorrect: false}},
	},
}

var questionsL7 = questionBank{
	[]question{
		{question: "على is a preposition meaning?",
			answer1: answer{text: "in", isCorrect: false},
			answer2: answer{text: "under", isCorrect: false},
			answer3: answer{text: "on", isCorrect: true}},
		{question: "The noun after a preposition has a_____? ",
			answer1: answer{text: "kasrah", isCorrect: true},
			answer2: answer{text: "fatah", isCorrect: false},
			answer3: answer{text: "dummah", isCorrect: false}},
		{question: "Arabic pronouns are different for each gender?",
			answer1: answer{text: "false", isCorrect: false},
			answer2: answer{text: "depands on context", isCorrect: false},
			answer3: answer{text: "true", isCorrect: true}},
		{question: "هُوَ is the pronoun meaning ?",
			answer1: answer{text: "they", isCorrect: false},
			answer2: answer{text: "she", isCorrect: false},
			answer3: answer{text: "he", isCorrect: true}},
		{question: "أنا means?",
			answer1: answer{text: "I", isCorrect: true},
			answer2: answer{text: "we", isCorrect: false},
			answer3: answer{text: "you", isCorrect: false}},
		{question: "There are ____ person pronoun groups",
			answer1: answer{text: "2", isCorrect: false},
			answer2: answer{text: "3", isCorrect: true},
			answer3: answer{text: "4", isCorrect: false}},

		{question: "المؤنث pronouns means?",
			answer1: answer{text: "dual", isCorrect: false},
			answer2: answer{text: "masculine", isCorrect: false},
			answer3: answer{text: "feminine", isCorrect: true}},
	},
}
